MSH|^~\&|EPIC|GMC||GMC|20150324152750|EDMD|ADT^A01|725402|T|2.3|||||||||
EVN|A01|20150324152750||ADT_EVENT|Model User^EMERGENCY^ATTENDING^PHYSICIAN^^^^^OHSA^^^^^GMC1|20150324152746|
PID|1||3100068696^^^EPI^MR||HUSSER^LONNIE||19880808|F|||^^^^^US^P|||||||6100215392|888-78-8965|||||||||||N||
PD1|||GRANT MEDICAL CENTER^^1013100|||||||||||||||
PV1|1|E|EDMG^B25^25^GMC1^R^^^^^^DEPID||||15802^BOEHMER^DAVID^C^^^^^STARPROV^^^^STARPROV|||Emergency||||||||EMERGENCY|6100215392|SELF||||||||||||||||||||||^^^GMC1^^^^^^^||20150324140900||||||22150830003
PV2||GENERAL||||||||||||||||||||N|||||||||||||||||||||||||||
ZPV|||||||||||||20150324152746||||||||
GT1|1|100046660|HUSSER^LONNIE^^||^^^^^US|||19880808|F|P/F|SLF|888-78-8965|||||||||||||||||||||||||||||||||||||
ZMP|1|||||N||||^^^^|||^^^^|||||^^^^||||^^^^||Not eligible for Medicare||||^^^^|||||^^^^|0|||^^^^|||||||||||||||||||||||||||||
T_50005_1T_50005_1{CONNID 0} {IPVERSION 4} {CLIENTIP 172.17.154.197} {CLIENTPORT 63143}
