MSH|^~\&|EPIC|GMC||GMC|20150324152810|ADTADM|ADT^A08|725406|T|2.3|||||||||
EVN|A08|20150324152810||REG_UPDATE|Model User^ADT^ADMIN^^^^^^OHSA^^^^^GMC1||
PID|1||3100067543^^^EPI^MR||JAMES^MICHAEL||19850123|M||Caucasian|90 LANE DRIVE^^MADISON^WI^53703^US^P||(976)824-0441^P^PH^^^976^8240441~^NET^Internet^test@gmail.com||ENG|SINGLE||6100215408|787-87-8787|||DECLINED||||||||N||
PD1|||GRANT MEDICAL CENTER^^1013100|155111^HOLT^ANGELA^^^^^^STARPROV^^^^STARPROV||||||||||||||
NK1|1|JAMES^BANNER^^|Friend|^^^^^US|(090)765-4534^^^^^090^7654534||Emergency Contact 1|||||||||||||||||||||||||||
NK1|2|||PO BOX 2710^^ROANOKE^VA^24001^US|(800)380-4681^^^^^800^3804681||Employer||||||ADVANCE AUTO PARTS||||||||||||||||||||1011|Full
PV1|1|O|GDG8^^^GMC1^^^^^^^DEPID|EL||||||||||Non-Healthcr||||OP IN BED|6100215408|SELF||||||||||||||||||||||^^^GMC1^^^^^^^||20150324||||||22150830005
PV2||||||||20150324||||||||||||||N|||||||||||||||||||||||||||
ZPV||||||||||||20150324152738|||||||||
DG1|1||^chest pain|chest pain||
GT1|1|100046259|JAMES^MICHAEL^^||90 LANE DRIVE^^MADISON^WI^53703^US|(976)824-0441^^^^^976^8240441||19850123|M|P/F|SLF|787-87-8787||||ADVANCE AUTO PARTS|PO BOX 2710^^ROANOKE^VA^24001^US|(800)380-4681^^^^^800^3804681||Full|||||||||||||||||||||||||||||
ZMP|1|||||N||||^^^^|||^^^^|||||^^^^||||^^^^||Not eligible for Medicare||||^^^^|||||^^^^|0|||^^^^|||||||||||||||||||||||||||||
T_50005_1T_50005_1{CONNID 0} {IPVERSION 4} {CLIENTIP 172.17.154.197} {CLIENTPORT 63143}
