MSH|^~\&|EPIC|GMC||GMC|20150324153305|EDRN|ADT^A03|725416|T|2.3|||||||||
EVN|A03|20150324153305||ADT_EVENT|Model User^EMERGENCY^NURSE^^^^^^OHSA^^^^^GMC1|20150324153200|
PID|1||3100068696^^^EPI^MR||HUSSER^LONNIE||19880808|F|||^^^^^US^P|||||||6100215392|888-78-8965|||||||||||N||
PD1|||GRANT MEDICAL CENTER^^1013100|||||||||||||||
PV1|1|E|EDMG^B25^25^GMC1^D^^^^^^DEPID||||15802^BOEHMER^DAVID^C^^^^^STARPROV^^^^STARPROV|||Emergency||||Non-Healthcr||||EMERGENCY|6100215392|SELF||||||||||||||||HOME||||||^^^GMC1^^^^^^^||20150324140900|20150324153200|||||22150830003
PV2||GENERAL||||||||||||||||||||N|||||||||||||||||||||||||||
ZPV|||||||||||||20150324152746||Discharge||||||
DG1|1|I9|764.10^Light-for-dates with signs of fetal malnutrition, unspecified (weight)^I9|Light-for-dates with signs of fetal malnutrition, unspecified (weight)||
GT1|1|100046660|HUSSER^LONNIE^^||^^^^^US|||19880808|F|P/F|SLF|888-78-8965|||||||||||||||||||||||||||||||||||||
ZMP|1|||||N||||^^^^|||^^^^|||||^^^^||||^^^^||Not eligible for Medicare||||^^^^|||||^^^^|0|||^^^^|||||||||||||||||||||||||||||
T_50005_1T_50005_1{CONNID 0} {IPVERSION 4} {CLIENTIP 172.17.154.197} {CLIENTPORT 63143}
