MSH|^~\&|EPIC|GMC||GMC|20150324153725|EDRN|ADT^A03|725443|T|2.3|||||||||
EVN|A03|20150324153725||ADT_EVENT|Model User^EMERGENCY^NURSE^^^^^^OHSA^^^^^GMC1|20150324153700|
PID|1||3100068696^^^EPI^MR||HUSSER^LONNIE||19880808|F|||^^^^^US^P|||||||6100215410|888-78-8965|||||||||||N||
PD1|||GRANT MEDICAL CENTER^^1013100|||||||||||||||
PV1|1|E|EDMG^B24^24^GMC1^D^^^^^^DEPID||||15802^BOEHMER^DAVID^C^^^^^STARPROV^^^^STARPROV|||Emergency||||Non-Healthcr||||EMERGENCY|6100215410|SELF||||||||||||||||SHORT TERM||||||^^^GMC1^^^^^^^||20150324153400|20150324153700|||||22150830006
PV2||GENERAL||||||||||||||||||||N|||||||||||||||||||||||||||
ZPV|||||||||||||20150324153448||||||||
GT1|1|100046660|HUSSER^LONNIE^^||^^^^^US|||19880808|F|P/F|SLF|888-78-8965|||||||||||||||||||||||||||||||||||||
ZMP|1|||||N||||^^^^|||^^^^|||||^^^^||||^^^^||Not eligible for Medicare||||^^^^|||||^^^^|0|||^^^^|||||||||||||||||||||||||||||
T_50005_1T_50005_1{CONNID 0} {IPVERSION 4} {CLIENTIP 172.17.154.197} {CLIENTPORT 63143}
